// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrVn235_eZPOFlJ-PnSFd434Q9ZLq4eQ',
    appId: '1:860949120657:web:1b2d8707fab6b060d3a130',
    messagingSenderId: '860949120657',
    projectId: 'app-project-7aeba',
    authDomain: 'app-project-7aeba.firebaseapp.com',
    storageBucket: 'app-project-7aeba.firebasestorage.app',
    measurementId: 'G-XSBFD4MFGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXiyfnhmVYJSQKOXXWjKdOMjNacchNhI4',
    appId: '1:860949120657:android:86a473fab95349b9d3a130',
    messagingSenderId: '860949120657',
    projectId: 'app-project-7aeba',
    storageBucket: 'app-project-7aeba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBeoRBhMWearKJi4xdzrqpPDvppvM3Mkk',
    appId: '1:860949120657:ios:a56c933567551139d3a130',
    messagingSenderId: '860949120657',
    projectId: 'app-project-7aeba',
    storageBucket: 'app-project-7aeba.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBeoRBhMWearKJi4xdzrqpPDvppvM3Mkk',
    appId: '1:860949120657:ios:a56c933567551139d3a130',
    messagingSenderId: '860949120657',
    projectId: 'app-project-7aeba',
    storageBucket: 'app-project-7aeba.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYrVn235_eZPOFlJ-PnSFd434Q9ZLq4eQ',
    appId: '1:860949120657:web:f548cf193144f07fd3a130',
    messagingSenderId: '860949120657',
    projectId: 'app-project-7aeba',
    authDomain: 'app-project-7aeba.firebaseapp.com',
    storageBucket: 'app-project-7aeba.firebasestorage.app',
    measurementId: 'G-CCHDY24W6Z',
  );
}
